### ISSUE TITLE
When I run the code, there is a question error

### ISSUE THREAD

**Issue by zhitiankai** [qiuqiangkong/sound_event_detection_dcase2017_task4#2]
8 tensor(0.1734, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward>)
/pytorch/aten/src/ATen/native/cudnn/RNN.cpp:1266: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
9 tensor(0.1780, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward>)
root        : INFO     ------------------------------------
root        : INFO     Iteration: 10

####################
(488, 1001, 17)
(488, 1000, 17)
Traceback (most recent call last):
  File "pytorch/main.py", line 415, in <module>
    train(args)
  File "pytorch/main.py", line 200, in train
    data_loader, reference_csv_path, tmp_submission_path)
  File "/work4/zhitiankai/sound_event_detection_dcase2017_task4-new/pytorch/evaluate.py", line 81, in evaluate
    output_dict['framewise_output'], average=None)
  File "/work4/zhitiankai/sound_event_detection_dcase2017_task4-new/pytorch/evaluate.py", line 22, in sed_average_precision
    assert strong_target.shape == framewise_output.shape
AssertionError
Why are shapes different (strong_target.shape) and( framewise_output.shape)?
could you help me?

**Comment by LXP-Never** [comment]
+1

**Comment by zhitiankai** [comment]
> +1

这个错误我解决了，就是帧数多了一帧，在feature.py改改就好

**Comment by LXP-Never** [comment]
能分享一下feature.py的代码吗？我想把这个项目跑起来，

**Comment by zhitiankai** [comment]
> 能分享一下feature.py的代码吗？我想把这个项目跑起来，

    # frames_num = frames_per_second * config.audio_duration + 1
    frames_num = frames_per_second * config.audio_duration 
改成这样子，就行了，你也在研究事件检测吗？有空一起研究一下

**Comment by LXP-Never** [comment]
好的，我这就去试试，非常感谢你

**Comment by LXP-Never** [comment]
我主攻语音频带扩展，然后偶尔会看看 声音分类、和回声消除

**Comment by zhitiankai** [comment]
> 我主攻语音频带扩展，然后偶尔会看看 声音分类、和回声消除
我是现在就在做声音分类

**Comment by qingkezyy** [comment]
> > 能分享一下 feature.py 的代码吗？我想把这个项目跑起来，
> 
> ```
> # frames_num = frames_per_second * config.audio_duration + 1
> frames_num = frames_per_second * config.audio_duration 
> ```
> 
> 改成这样子，就行了，你也在研究事件检测吗？有空一起研究一下



> > +1
> 
> 这个错误我解决了，就是帧数多了一帧，在 feature.py 改改就好

您好，我按照您的操作修改了 feature.py 之后，还是在迭代到1000时遇到了错误。
错误如下：
997 tensor(0.1682, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
998 tensor(0.1512, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
999 tensor(0.1822, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
root        : INFO     ------------------------------------
root        : INFO     Iteration: 1000
Traceback (most recent call last):
  File "pytorch/main.py", line 415, in <module>
    train(args)
  File "pytorch/main.py", line 199, in train
    (statistics, _) = evaluator.evaluate(
  File "/public/home/03455/ZYY/sound_event_detection_dcase2017_task4-master/pytorch/evaluate.py", line 76, in evaluate
    statistics['framewise_ap'] = sed_average_precision(
  File "/public/home/03455/ZYY/sound_event_detection_dcase2017_task4-master/pytorch/evaluate.py", line 19, in sed_average_precision
    assert strong_target.shape == framewise_output.shape
AssertionError
root        : INFO     Namespace(augmentation='mixup', batch_size=32, cuda=True, dataset_dir='/public/home/03455/ZYY/data/DCASE2017/TASK4', filename='main', holdout_fold='1', learning_rate=0.0001, loss_type='clip_bce', mini_data=False, mode='train', model_type='Cnn_9layers_Gru_FrameAtt', resume_iteration=50000, stop_iteration=70000, workspace='/public/home/03455/ZYY/data/cnn+transformer')
root        : INFO     Using GPU.
/public/home/03455/anaconda3/envs/ADMAE/lib/python3.8/site-packages/torchlibrosa/stft.py:193: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = librosa.util.pad_center(fft_window, n_fft)
root        : INFO     Load resume model from /public/home/03455/ZYY/data/cnn+transformer/checkpoints/main/holdout_fold=1/model_type=Cnn_9layers_Gru_FrameAtt/loss_type=clip_bce/augmentation=mixup/batch_size=32/50000_iterations.pth
Traceback (most recent call last):
  File "pytorch/main.py", line 415, in <module>
    train(args)
  File "pytorch/main.py", line 129, in train
    resume_checkpoint = torch.load(resume_checkpoint_path)
  File "/public/home/03455/anaconda3/envs/ADMAE/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/public/home/03455/anaconda3/envs/ADMAE/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/public/home/03455/anaconda3/envs/ADMAE/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/03455/ZYY/data/cnn+transformer/checkpoints/main/holdout_fold=1/model_type=Cnn_9layers_Gru_FrameAtt/loss_type=clip_bce/augmentation=mixup/batch_size=32/50000_iterations.pth'
/public/home/03455/anaconda3/envs/ADMAE/lib/python3.8/site-packages/torchlibrosa/stft.py:193: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = librosa.util.pad_center(fft_window, n_fft)
Traceback (most recent call last):
  File "pytorch/main.py", line 418, in <module>
    inference_prob(args)
  File "pytorch/main.py", line 332, in inference_prob
    checkpoint = torch.load(checkpoint_path)
  File "/public/home/03455/anaconda3/envs/ADMAE/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/public/home/03455/anaconda3/envs/ADMAE/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/public/home/03455/anaconda3/envs/ADMAE/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/03455/ZYY/data/cnn+transformer/checkpoints/main/holdout_fold=1/model_type=Cnn_9layers_Gru_FrameAtt/loss_type=clip_bce/augmentation=mixup/batch_size=32/70000_iterations.pth'
Traceback (most recent call last):
  File "utils/optimize_thresholds.py", line 288, in <module>
    optimize_at_thresholds(args)
  File "utils/optimize_thresholds.py", line 143, in optimize_at_thresholds
    score_calculator = AudioTaggingScoreCalculator(prediction_path)
  File "utils/optimize_thresholds.py", line 26, in __init__
    self.output_dict = pickle.load(open(prediction_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/03455/ZYY/data/cnn+transformer/predictions/main/holdout_fold=1/model_type=Cnn_9layers_Gru_FrameAtt/loss_type=clip_bce/augmentation=mixup/batch_size=32/70000_iterations.prediction.test.pkl'
您能帮帮我吗？
